### ISSUE TITLE
GeoIP.dat Error

### ISSUE THREAD

**Issue by Darkcast** [Swordf1sh/Moderat#16]
Traceback (most recent call last):
  File "Moderat.py", line 36, in <module>
    geo_ip_database = pygeoip.GeoIP('assets\\GeoIP.dat')
  File "/root/Moderat/libs/pygeoip/__init__.py", line 75, in __call__
    cls._instances[filename] = super(_GeoIPMetaclass, cls).__call__(*args, **kwargs)
  File "/root/Moderat/libs/pygeoip/__init__.py", line 118, in __init__
    self._fp = codecs.open(filename, 'rb', ENCODING)
  File "/usr/lib/python2.7/codecs.py", line 878, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'assets\\GeoIP.dat'

**Comment by Swordf1sh** [comment]
Are you using Windows os?
Check if GeoIP.dat exists in directory <Moderat Dir>\assets\

**Comment by Darkcast** [comment]
I am using Kali Linux 2.0 and yes geoip is on the moderat dir 
➜  Moderat git:(master) ✗ locate GeoIP.dat          
/root/Moderat/assets/GeoIP.dat
/usr/share/GeoIP/GeoIP.dat
➜  Moderat git:(master) ✗

**Comment by Swordf1sh** [comment]
Sorry, this program only supports Windows yet

**Comment by Darkcast** [comment]
No bueno :(

**Comment by egy-saboteur** [comment]
hi pro i cant run ur rat
plz tell me how to run it in winxp machine

**Comment by Swordf1sh** [comment]
Make sure you have installed python 2.7 and python libraries PyQt4, PIL, PyAudio
then run moderat.py

**Comment by egy-saboteur** [comment]
how to install python libraries PyQt4, PIL, PyAudio
give me video explain that >>> plz

**Comment by Swordf1sh** [comment]
All Python libraries [http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4](Unofficial Windows Binaries for Python Extension Packages)

after downloading use pip to install

example:
`pip install Pillow-3.3.0-cp27-cp27m-win32.whl`
