### ISSUE TITLE
help me to convert project to exe

### ISSUE THREAD

**Issue by nour0nour** [Swordf1sh/Moderat#20]
Can u help me ?
i can't convert project to exe
I try alot of many  but i fails
i used  py2exe , pyinstaller and cx_freeze
but .............. i fails .
thanx

**Comment by Swordf1sh** [comment]
Client builder under development and it will release soon

for testing you can start cmd from Moderat/Client/Win32/ folder  and build client.py with pyinstaller

example cmd: 
`C:\Moderat\Client\win32\> python C:\PyInstaller\PyInstaller.py --noconsole --onefile client.py`
